version: "3.8"

services:
  app:
    build: .
    working_dir: /app
    volumes:
      - ./src:/app/src
    expose:
      - 3000
    command: "yarn cy:start"

  cypress:
    build:
      context: .
      dockerfile: Dockerfile-cy
    working_dir: /e2e
    volumes:
      - ./:/e2e
      - /e2e/node_modules
    environment:
      - CYPRESS_baseUrl=http://app:3000
    depends_on:
      - app
